execute @e[score_mode_min=0,score_mode=1,score_diffnum=1,score_diffnum_min=1] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=70] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=2,score_diffnum=2] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=55] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=3,score_diffnum=3] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=35] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=4,score_diffnum=4] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=25] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=5,score_diffnum=5] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=25] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=6,score_diffnum=6] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=10] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
execute @e[name=dt,score_mode_min=0,score_mode=1,score_diffnum_min=7,score_diffnum=7] ~ ~ ~ execute @e[type=armor_stand,name=dt,score_drop_min=5] ~ ~ ~ execute @r[type=area_effect_cloud,name=drop] ~ ~ ~ summon Creeper ~ ~ ~ {NoGravity:1b,Fuse:1,ExplosionRadius:2,CustomName:"Tracking Missle...",Attributes:[{Name:"generic.followRange",Base:500}]}
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=1,score_diffnum=1,score_drop_min=70,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=2,score_diffnum=2,score_drop_min=55,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=3,score_diffnum=3,score_drop_min=35,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=4,score_diffnum=4,score_drop_min=25,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=5,score_diffnum=5,score_drop_min=25,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=6,score_diffnum=6,score_drop_min=10,score_mode_min=0,score_mode=1] drop 0
scoreboard players set @e[type=armor_stand,name=dt,score_diffnum_min=7,score_diffnum=7,score_drop_min=5,score_mode_min=0,score_mode=1] drop 0