effect @a[tag=ingame,score_speed_min=1] speed 1 0 true
effect @a[tag=ingame,score_speed_min=2] speed 1 1 true
effect @a[tag=ingame,score_speed_min=3] speed 1 2 true
effect @a[tag=ingame,score_speed_min=4] speed 1 3 true
effect @a[tag=ingame,score_speed_min=5] speed 1 4 true
effect @a[tag=ingame,score_speed_min=6] speed 1 5 true
effect @a[tag=ingame,score_speed_min=7] speed 1 6 true
effect @a[tag=ingame,score_speed_min=8] speed 1 7 true
effect @a[tag=ingame,score_speed_min=9] speed 1 8 true
effect @a[tag=ingame,score_speed_min=10] speed 1 9 true
effect @a[tag=ingame,score_resistance_min=1] resistance 1 0 true
effect @a[tag=ingame,score_resistance_min=2] resistance 1 1 true
effect @a[tag=ingame,score_resistance_min=3] resistance 1 2 true
effect @a[tag=ingame,score_resistance_min=4] resistance 1 3 true
effect @a[tag=ingame,score_resistance_min=5] resistance 1 4 true
effect @a[tag=ingame,score_resistance_min=6] resistance 1 5 true
effect @a[tag=ingame,score_resistance_min=7] resistance 1 6 true 
effect @a[tag=ingame,score_resistance_min=8] resistance 1 7 true 
effect @a[tag=ingame,score_resistance_min=9] resistance 1 8 true
effect @a[tag=ingame,score_resistance_min=10] resistance 1 9 true
effect @a[tag=ingame,score_jumpboost_min=1] jump_boost 1 0 true
effect @a[tag=ingame,score_jumpboost_min=2] jump_boost 1 1 true
effect @a[tag=ingame,score_jumpboost_min=3] jump_boost 1 2 true
effect @a[tag=ingame,score_jumpboost_min=4] jump_boost 1 3 true
effect @a[tag=ingame,score_jumpboost_min=5] jump_boost 1 4 true
effect @a[tag=ingame,score_jumpboost_min=6] jump_boost 1 5 true
effect @a[tag=ingame,score_jumpboost_min=7] jump_boost 1 6 true
effect @a[tag=ingame,score_jumpboost_min=8] jump_boost 1 7 true
effect @a[tag=ingame,score_jumpboost_min=9] jump_boost 1 8 true
effect @a[tag=ingame,score_jumpboost_min=10] jump_boost 1 9 true
effect @a[tag=ingame,score_strength_min=1] strength 1 0 true
effect @a[tag=ingame,score_strength_min=2] strength 1 1 true
effect @a[tag=ingame,score_strength_min=3] strength 1 2 true
effect @a[tag=ingame,score_strength_min=4] strength 1 3 true
effect @a[tag=ingame,score_strength_min=5] strength 1 4 true
effect @a[tag=ingame,score_strength_min=6] strength 1 5 true
effect @a[tag=ingame,score_strength_min=7] strength 1 6 true
effect @a[tag=ingame,score_strength_min=8] strength 1 7 true
effect @a[tag=ingame,score_strength_min=9] strength 1 8 true
effect @a[tag=ingame,score_strength_min=10] strength 1 9 true